apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        # without port 5000 as ingress is listening on simple 443
        # will be forwarded to the service with port 5000
        image: registry.rd.localhost/piotr-cicd/sample-spring-kotlin:1.5.5
        ports:
        - containerPort: 8080
